######################################################################
# Automatically generated by qmake (3.0) Do. M�r. 24 14:00:31 2016
######################################################################

TEMPLATE = app
TARGET = street-light-simulator
INCLUDEPATH += .
#QT += gui
QT += widgets
#QT += qml
QT += quick
CONFIG += staticlib
CONFIG += release qt debug

# Input
SOURCES += main.cpp 
RESOURCES += qml.qrc \
    ressources.qrc
